# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('norma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aviso', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(b'Al dia', 1), (b'Cada intervalo', 2)])),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('mese', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=120)),
                ('titulo', models.CharField(max_length=45)),
                ('dias_aviso', models.IntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Cargo')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.Formato')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacion.Aviso')),
            ],
        ),
        migrations.AddField(
            model_name='periodicidad',
            name='recordatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacion.Recordatorio'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='recordatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacion.Recordatorio'),
        ),
    ]
