# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import validable.binary


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', validable.binary.ByteAField()),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.CreateModel(
            name='Validable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('identificador', models.CharField(default=None, max_length=45, null=True)),
                ('class_name', models.CharField(default=None, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Validable',
                'verbose_name_plural': 'Validables',
            },
        ),
        migrations.AddField(
            model_name='template',
            name='validable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='validable.Validable'),
        ),
    ]
