# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usr', '0001_initial'),
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Empleado'),
        ),
        migrations.AddField(
            model_name='registro',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.Formulario'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.Campo'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.Registro'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='valor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.Valor'),
        ),
        migrations.AddField(
            model_name='campo',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.Formulario'),
        ),
        migrations.AddField(
            model_name='campo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.Tipo'),
        ),
    ]
