# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
        ('formulario', '0002_auto_20160922_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('revision', models.NullBooleanField(choices=[(None, b'Pendiente'), (True, b'Arobado'), (False, b'Rechazado')], default=None)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='revisor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='revisor', to='usr.Empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.Registro'),
        ),
    ]
