# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20161118_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
