# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20161118_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formulario.Registro'),
        ),
    ]
