# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20161118_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='correccion_de',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correccion', to='formulario.Revision'),
        ),
    ]
