# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_registro_correccion_de'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=145)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.Formulario')),
            ],
        ),
        migrations.RemoveField(
            model_name='campo',
            name='formulario',
        ),
        migrations.AddField(
            model_name='campo',
            name='ver_como',
            field=models.IntegerField(choices=[(0, b'De arriba abajo'), (1, b'En la misma lina')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo',
            name='forma',
            field=models.IntegerField(choices=[(0, b'Binario'), (1, b'Decimal'), (2, b'Entero'), (3, b'Cadena'), (4, b'Parrafo'), (5, b'Fecha'), (6, b'Hora'), (7, b'Fecha/Hora'), (8, b'Obciones'), (9, b'Referencia')]),
        ),
    ]
