# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_auto_20170227_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formulario.Grupo'),
            preserve_default=False,
        ),
    ]
