# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_campo_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='ver_como',
        ),
    ]
