# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_remove_campo_ver_como'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='ver_como',
            field=models.CharField(choices=[(b'block', b'De arriba abajo'), (b'inline', b'En la misma lina')], default='block', max_length=45),
            preserve_default=False,
        ),
    ]
