# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('completado', models.BooleanField()),
                ('fecha_estimada', models.DateTimeField()),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdquisiscionMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Contratista')),
            ],
        ),
        migrations.CreateModel(
            name='Gantt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('uso_unico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Contrato')),
                ('dependencias', models.ManyToManyField(blank=True, to='epc.OrdenTrabajo')),
                ('materiales', models.ManyToManyField(through='epc.AdquisiscionMaterial', to='epc.Material')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoGrafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epc.OrdenTrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAdquisiscion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Proyecto'),
        ),
        migrations.AddField(
            model_name='gantt',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epc.Proyecto'),
        ),
        migrations.AddField(
            model_name='adquisiscionmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Material'),
        ),
        migrations.AddField(
            model_name='adquisiscionmaterial',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.OrdenTrabajo'),
        ),
        migrations.AddField(
            model_name='adquisiscionmaterial',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.TipoAdquisiscion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.OrdenTrabajo'),
        ),
    ]
