# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdquisiscionMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='uso_unico',
            field=models.BooleanField(default=False),
        ),
        
        migrations.AddField(
            model_name='adquisiscionmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Material'),
        ),
        migrations.AddField(
            model_name='adquisiscionmaterial',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.OrdenTrabajo'),
        ),
    ]
