# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0002_auto_20160924_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Grupo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Contratista')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epc.Grupo'),
        ),
    ]
