# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0003_remove_ordentrabajo_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='materiales',
            field=models.ManyToManyField(through='epc.AdquisiscionMaterial', to='epc.Material'),
        ),
    ]
