# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0003_auto_20161001_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contratista',
            new_name='Personal',
        ),
    ]
