# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0004_ordentrabajo_materiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAdquisiscion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
