# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('epc', '0004_auto_20161001_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='contratista',
        ),
        migrations.AddField(
            model_name='personal',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empleado'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='contratista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Personal'),
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
