# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0006_auto_20161001_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_estimada',
        ),
        migrations.AddField(
            model_name='actividad',
            name='dias_estimados',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
