# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0006_adquisiscionmaterial_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='materiales',
        ),
        migrations.AddField(
            model_name='actividad',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
