# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 13:33
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0008_actividad_poscicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['poscicion']},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='orden',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.OrdenTrabajo'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='poscicion',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
