# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0010_auto_20161009_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='poscicion',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
