# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0010_actividad_completado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='completado',
        ),
    ]
