# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20160922_2042'),
        ('epc', '0011_auto_20161116_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.Formulario'),
        ),
    ]
