# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0011_remove_actividad_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
