# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0012_auto_20160920_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='completado',
            field=models.BooleanField(),
        ),
    ]
