# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0013_actividad_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='revisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revisor', to='epc.Personal'),
            preserve_default=False,
        ),
    ]
