# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0013_auto_20160920_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_estimada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
