# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0015_auto_20160921_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Contratista')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='contratista',
        ),
    ]
