# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0017_ordentrabajo_contratista'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoGrafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epc.OrdenTrabajo')),
            ],
        ),
    ]
