# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0019_ordentrabajo_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gantt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.Proyecto')),
            ],
        ),
    ]
