# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0021_auto_20160922_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='nombre_corto',
            field=models.CharField(default='Orden1', max_length=45),
            preserve_default=False,
        ),
    ]
