# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name=b'a\xc3\xb1o')),
            ],
            options={
                'verbose_name': 'A\xf1o',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cesa', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Cesantias')),
                ('intc', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Intereses sobre cesantias')),
                ('prim', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Primas de servicio')),
                ('vaca', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Vacaciones')),
                ('hexd', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Horas extras diurnas')),
                ('hnoc', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Horas nocturnas')),
                ('hexn', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Horas extras nocturnas')),
                ('hord', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Horas ordinarias dominicales')),
                ('hxdd', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Horas extras diurnas dominicales')),
                ('hxnd', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Horas extras nocturnas dominicales')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias_anio', models.IntegerField(default=360, verbose_name=b'Dias del a\xc3\xb1o')),
                ('porc_cesa', models.FloatField(default=0.12, verbose_name=b'Porcentaje de cesantias')),
                ('ango_vaca', models.IntegerField(default=2, verbose_name=b'A\xc3\xb1os por vacaciones')),
                ('porc_hexd', models.FloatField(default=1.25, verbose_name=b'Porcentaje de horas extras diurnas')),
                ('porc_hnoc', models.FloatField(default=1.35, verbose_name=b'Porcentaje de horas nocturnas')),
                ('porc_hexn', models.FloatField(default=1.75, verbose_name=b'Porcentaje de horas extras nocturnas')),
                ('porc_hord', models.FloatField(default=1.75, verbose_name=b'Porcentaje de horas ordinarias dominicales')),
                ('porc_hxdd', models.FloatField(default=2, verbose_name=b'Porcentaje de horas extras diurnas dominicales')),
                ('porc_hxnd', models.FloatField(default=2.5, verbose_name=b'Porcentaje de horas extras nocturnas dominicales')),
                ('agno_vaca', models.FloatField(default=2, verbose_name=b'Divisor de a\xc3\xb1os por vacaciones')),
                ('dia_cmes', models.IntegerField(default=1, verbose_name=b'Dia corte mensual')),
                ('dia_cqui', models.IntegerField(default=15, verbose_name=b'Dia corte quinsenal')),
                ('dia_canu', models.IntegerField(default=31, verbose_name=b'Dia de corte anual')),
                ('mes_canu', models.IntegerField(default=12, verbose_name=b'Mes de corte anual')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('documento', models.FileField(upload_to=b'contratos')),
                ('firmado', models.BooleanField()),
                ('horas_dia', models.IntegerField()),
                ('modalidad', models.IntegerField(choices=[(1, b'Mensual'), (0, b'Quinsenal')])),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('bonificacion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('razons', models.CharField(max_length=100)),
                ('ident', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, upload_to=b'empresa/')),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('calculos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Calculos')),
                ('configuracion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Configuracion')),
            ],
        ),
        migrations.CreateModel(
            name='HorasExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('horas', models.IntegerField()),
                ('tipo', models.BooleanField(choices=[(True, b'Diurna'), (False, b'Nocturna')], default=True)),
                ('dominical', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Contrato')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Jefes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionNomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_corte', models.DateField()),
                ('dias', models.IntegerField(verbose_name=b'Dias trabajados')),
                ('cesa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Cesantias acumuladas')),
                ('intc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Intereses sobre cesantias acumulados')),
                ('prim', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Primas de servicio acumuladas')),
                ('hord', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas ordinarias')),
                ('hexd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas extras diurnas')),
                ('hexn', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas extras nocturnas')),
                ('hxdd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas extras diurnas dominicales')),
                ('hxnd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas extras nocturnas dominicales')),
                ('totl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Total devengado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Contrato')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educacion', models.TextField(blank=True)),
                ('formacion', models.TextField(blank=True)),
                ('habilidades', models.TextField(blank=True)),
                ('experiencia', models.TextField(blank=True)),
                ('cargo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Cargo')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='superior',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empleado'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Departamento'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Contrato'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empleado'),
        ),
    ]
