# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='salario',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
