# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20161116_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='cesa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Cesantias acumuladas $'),
        ),
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='hexd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas extras diurnas $'),
        ),
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='hexn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas extras nocturnas $'),
        ),
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='hord',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas ordinarias $'),
        ),
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='hxdd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas extras diurnas dominicales $'),
        ),
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='hxnd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Horas extras nocturnas dominicales $'),
        ),
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='intc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Intereses sobre cesantias acumulados $'),
        ),
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='prim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Primas de servicio acumuladas $'),
        ),
        migrations.AlterField(
            model_name='liquidacionnomina',
            name='totl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name=b'Total devengado $'),
        ),
    ]
